  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/pt/"
  
  [[main]]
  name = "Posts"
  weight = 200
  identifier = "post"
  url = "/post/"

  [[main]]
  name = "disciplinas"
  weight = 300
  identifier = "disciplinas"
  url = "/disciplinas/"

#  [[main]]
#  name = "Contate-me"
#  weight = 400
#  identifier = "contact"
#  url = "/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"