  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/en/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "post"
  url = "/en/post/"

  [[main]]
  name = "Courses"
  weight = 300
  identifier = "courses"
  url = "/en/courses/"

#  [[main]]
#  name = "Contact"
#  weight = 400
#  identifier = "contact"
#  url = "/en/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"